### ISSUE TITLE
Error is not recoverable

### ISSUE THREAD

**Issue by manujchandra** [maximtrp/ranger-archives#10]
![Screenshot from 2021-06-14 16-59-38](https://user-images.githubusercontent.com/15191493/121885897-5864ec00-cd32-11eb-8fb6-67d01410fc2a.png)

I am using the latest version of the plugin. I am unable to extract any archives. But I can do so successfully using CLI and Nautilus. Only in ranger its giving the error.

ranger version: ranger 1.9.3
Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Locale: en_US.UTF-8

I was working earlier. :compress is working fine. Only :extract is having this problem.

**Comment by maximtrp** [comment]
Thank you for reporting! Could you please start **ranger** in debug mode (**-d**, **--debug**) and post the log here?

**Comment by manujchandra** [comment]
```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Locale: en_US.UTF-8
Current file: '/home/manuj/Productivity_System/WORK TOKENS/zTOKENS_REMAINING.tar.xz'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 423, in work
    next(item.load_generator)
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 218, in generate
    self.fm.notify(read, bad=True)
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: /usr/bin/tar: -C: Cannot open: No such file or directory


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 371, in loop
    loader.work()
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 428, in work
    self.fm.notify(
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Loader work process failed: Extracting: zTOKENS_REMAINING.tar.xz (Percent: 0)

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by maximtrp** [comment]
Please update the plugin and check if it is working correctly now.

**Comment by manujchandra** [comment]
Seems to be working now. Thanks!
