### ISSUE TITLE
Error while using `:extract`: Unexpected end of input stream.

### ISSUE THREAD

**Issue by StarryReverie** [maximtrp/ranger-archives#15]
![bH72TS.png](https://s1.ax1x.com/2022/03/12/bH72TS.png)

```plain
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Locale: zh_CN.UTF-8
Current file: '/home/ctj12461/tmp/tmp.zip'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/loader.py", line 423, in work
    next(item.load_generator)
  File "/usr/lib/python3.10/site-packages/ranger/core/loader.py", line 218, in generate
    self.fm.notify(read, bad=True)
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 371, in loop
    loader.work()
  File "/usr/lib/python3.10/site-packages/ranger/core/loader.py", line 428, in work
    self.fm.notify(
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Loader work process failed: Extracting: tmp.zip (Percent: 0)

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

The version of the plugin is the latest.
System: Arch Linux x86_64

**Comment by maximtrp** [comment]
Do you have `unzip` installed? Is it working correctly? Are you trying to overwrite the already extracted file (of the file with the same name as the one in the archive)?

**Comment by StarryReverie** [comment]
It works well after installing unzip. Thank you.
